console.log(document.getElementById('usuario'))
console.log(document.getElementsByTagName('input'))
console.log(document.getElementsByClassName('input'))
console.log(document.getElementsByName('nome'))
console.log(document.querySelector('#usuario'))
console.log(document.querySelector('campo_texto'))
console.log(document.querySelector('[data-personalizado]'))